[project]
name = "standard-smtpd"
version = "3.11.9"
description = "Standard library smtpd redistribution. \"dead battery\"."
keywords = ["stdlib"]
authors = [
    { name = "Python Developers", email = "python-deadlib@youknowone.org" }
]
readme = "README.rst"
license = {name = "PSF", file = "LICENSE"}
classifiers = [
    "License :: OSI Approved :: Python Software Foundation License",
    "Topic :: Software Development :: Libraries",
    "Programming Language :: Python :: 3",
]
dependencies = [
    "standard-asyncore; python_version >= '3.12'",
    "standard-asynchat; python_version >= '3.12'",
]

[tool.setuptools.packages]
find = {include = ["smtpd*"]}

[project.urls]
"Homepage" = "https://github.com/youknowone/python-deadlib"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
