[project]
name = "standard-crypt"
version = "3.12.2"
description = "Standard library crypt redistribution. \"dead battery\"."
keywords = ["stdlib"]
authors = [
    { name = "Python Developers", email = "python-deadlib@youknowone.org" }
]
readme = "README.rst"
license = { text = "PSF-2.0" }
classifiers = [
    "License :: OSI Approved :: Python Software Foundation License",
    "Topic :: Software Development :: Libraries",
    "Programming Language :: Python :: 3",
]

[tool.setuptools.packages]
find = {include = ["crypt*"]}

[project.urls]
"Homepage" = "https://github.com/youknowone/python-deadlib"

[build-system]
requires = [
    "setuptools>=75.0",
    "deprecated-_crypt-alternative>=0.1.0",
]
build-backend = "setuptools.build_meta"
